### ISSUE TITLE
integration with other open whatsapp modules

### ISSUE THREAD

**Issue by InushaDeSilva** [pruizlezcano/whatsapp-bot#1]
i have another whatsapp module built, how can i add this api to it or intergrete this in the the previos open whatsapp module?

**Comment by pruizlezcano** [comment]
I think what you are asking is how can you add these commands in another bot. If so, you have two options:
- Modify the commands files to have the same structure as mine and copy them to the `commands` folder.
- Modify my commands to add them to the ones you have now. But you have to know that some commands like `help` may not work.
